* GUI Crash
High Priority

Steps to reproduce the bug:
- Boot
- Type =bg sand RET=
- Switch focus to that GUI window (click selector in taskbar)
- Hold =Alt= and press =Q=
- Huzzah! kernel null dereference

* Timer Overhaul
Medium Priority

The LensorOS kernel needs the following time-related functionality; currently, we are kind of configuring multiple pieces of hardware and ending up with multiple ways of doing the same thing. Not only that, but, a lot of things in the kernel are calling into hardware code, rather than a nice abstraction. We want clean layers, and this would be achieving that.

#+begin_example
USERSPACE
   |> SYSCALLS
HIGH LEVEL KERNEL
   |> HIGH LEVEL KERNEL MODULES (HLKMs)
KERNEL DRIVERS
   |> HARDWARE DRIVERS
HARDWARE
#+end_example

Currently, the /High Level Kernel/ , or /HLK/, is kind of mixed in with the hardware drivers.

The idea is simple: we define high level kernel modules and APIs to use them, then, syscalls may only use those APIs.

A particular system, at boot, will fill in as many high level kernel module interfaces as possible with corresponding drivers (or wrappers around them).

This just focuses on the first well-defined high level kernel module, the time module.

#+begin_src c++
  namespace Time {

  // These need to be set by the system initialization; once set, we
  // don't need to keep finding new solutions for the same problem.
  namespace Interface {

  // @return approximate UNIX Epoch time when the computer started.
  uintptr_t unix_time_at_boot = 0;

  // The amound of nanoseconds in-between two timer ticks.
  uintptr_t tick_duration_in_nanoseconds = 0;

  // Ticks happen at a frequency of @c tick_frequency().
  // @return the current tick value.
  const uintptr_t* tick_value = nullptr;

  }  // namespace Interface

  // milliseconds_per_second and friends constexpr constants...

  inline uintptr_t tick_time_now() {
      if (Interface::tick_value)
          return *Interface::tick_value;
      return 0;
  }

  inline uintptr_t tick_duration_in_nanoseconds() {
      return Interface::tick_duration_in_nanoseconds;
  }

  inline uintptr_t tick_frequency() {
      auto nanosecond_duration = tick_duration_in_nanoseconds();
      if (nanosecond_duration)
          return nanoseconds_per_second / nanosecond_duration;
      return 0;
  }

  inline uintptr_t unix_time_boot() {
      return Interface::unix_time_at_boot;
  }

  inline uintptr_t unix_time_now() {
      auto ticks_nanoseconds = tick_time_now() * tick_duration_in_nanoseconds();
      auto ticks_seconds = ticks_nanoseconds / nanoseconds_per_second;
      return unix_time_at_boot + ticks_seconds;
  }

  // struct tm
  // gmtime(), mktime()

  }  // namespace Time
#+end_src

The basic idea is this: the API is implemented only in terms of the nested =Interface=, and the =Interface= is initialized at boot time (or as possible).

* Dynamic Linker
Medium Priority

It's honestly not that complicated.

The kernel, when it sees a =PT_INTERP= program header in the ELF file it is loading, loads the dynamic linker shared object into memory, the same way it does any other ELF file. The loader goes on to set up the entry point to the dynamic linker shared object, not the loaded executable. It passes arguments to the dynamic linker like the dynamic linker's and the loaded program's object base, symbol table, and string table address.

The dynamic linker in userspace is executing in a prekernel-like environment, where global variables are not accessible due to memory not being mapped yet (it hasn't relocated itself).

Using only the addresses passed to us and local variables, the dynamic linker first finds it's own GOT and applies relocations to itself... It uses it's own dynamic section (=_DYNAMIC= symbol) to find =DT_RELA*= entries for the info of the relocation table, which it can then use to perform it's own relocations (yay, globals!).

Once the dynamic linker is bootstrapped, we then loop through the =DT_NEEDED= entries *of the loaded program*, and load each of those files into memory. The dynamic linker keeps track of all libraries that have been loaded already, such as to not load the same library twice.

Once the loaded program and every dependency, recursively, has been loaded into memory, we perform relocations on each loaded object. Once relocations are performed on an object, the dynamic linker executes =DT_INIT=/=DT_INIT_ARRAY= functions (in reverse load order).

Above describes immediate binding; utilize =-Wl,-z,now=. For lazy binding, we would simply need a runtime resolver function that is called from a state-saving assembly stub (called from the PLT stub), and we'd write the function pointer into the GOT then.

* Flesh out the Network Stack
Medium Priority

** UDP -- User Datagram Protocol

A very simple header you can bang on to just about any payload.

Technologies built on UDP:
- DHCP :: Dynamic Host Configuration Protocol
  This lets you get an IP address! Then you can respond to your very own ARPs.
- DNS :: Domain Name System
  This lets you turn human-readable URLs into computer-readable IPs!
- NTP :: Network Time Protocol
  This lets you sync your time with everyone else's time!

* FAT Fixups
Low Priority

Creating directories, allocating first cluster for new directories, etc.

* Intel HDA Audio Driver
Low Priority

Then we can write an audio server, and hook userspace applications up with audio capabilities!

It would be really cool to have an audio visualizer userspace program.

* Bootloader Transition
Low Priority

Should be "invisible" to the kernel, but we want to transition to the RADII bootloader.

* ACPI AML Interpreter
Low Priority

Firmware interaction, basically. Yes, modern firmware is implemented in the form of a high level dynamic language...

[[https://codeberg.org/LensPlaysGames/LensorOS/issues/55][Issue #55]] tracks this feature.
