* Implement A Graphical Compositor Program
Medium Priority

- Fix: read/write() need to be configurable for non-blocking, or something of that nature.

** Window Stack

What other OSes might call a "task bar".

I want the compositor to draw it's own portion of the screen, where the compositor state is displayed, like currently open windows.

The mouse should be able to select the active window (z order) as well as the focused window (focus state) with mouse clicks

* Flesh out the Network Stack
Low Priority

** ARP -- Address Resolution Protocol

This can get you a gateway address, which means you can talk to the rest of the world. Yay!

** UDP -- User Datagram Protocol

A very simple header you can bang on to just about any payload.

Technologies built on UDP:
- DHCP :: Dynamic Host Configuration Protocol
  This lets you get an IP address! Then you can respond to your very own ARPs.
- DNS :: Domain Name System
  This lets you turn human-readable URLs into computer-readable IPs!
- NTP :: Network Time Protocol
  This lets you sync your time with everyone else's time!

* PSF Screen Font Sharing
Low Priority

It's so common that I think we should just map the PSF screen font in every process, since the kernel will always have it loaded anyway. Compositor can take advantage of this, terminal programs, etc. Who doesn't need a font?
