* Implement A Graphical Compositor Program
Medium Priority

** Window Stack Selector Identification

Currently, it's hard to tell which selector refers to which window.
Even just a simple unique color or number inside the box would help.

* Flesh out the Network Stack
Medium Priority

** UDP -- User Datagram Protocol

A very simple header you can bang on to just about any payload.

Technologies built on UDP:
- DHCP :: Dynamic Host Configuration Protocol
  This lets you get an IP address! Then you can respond to your very own ARPs.
- DNS :: Domain Name System
  This lets you turn human-readable URLs into computer-readable IPs!
- NTP :: Network Time Protocol
  This lets you sync your time with everyone else's time!

* PSF Screen Font Sharing
Low Priority

It's so common that I think we should just map the PSF screen font in every process, since the kernel will always have it loaded anyway. Compositor can take advantage of this, terminal programs, etc. Who doesn't need a font?

* ACPI AML Interpreter
Low Priority

Firmware interaction, basically. Yes, modern firmware is implemented in the form of a high level dynamic language...

[[https://codeberg.org/LensPlaysGames/LensorOS/issues/55][Issue #55]] tracks this feature.
