* Implement A Graphical Compositor Program
Medium Priority

Basically, I want =stdout= to:

- Open a socket, =!GUI=, for listening.
- When a connection comes in on this socket, accept it, allocate shared memory large enough for a copy of the entire framebuffer, write  the shared memory region id to the accepted connection file descriptor so the client can read it. Bookkeep this shared memory id has a window (shared memory region id and address), where it is (with depth!), and possibly anything else the client chose to share with us (eventually).

The client reads the shared memory ID from the socket, acquires the shared memory, and writes it's graphical pixel data into this memory. It hopes and prays the compositor program (us, we) will actually display it.

- "Occasionally" repaint, drawing the visible portions of each book-kept window's shared memory region onto the actual portion of the real framebuffer it needs to be drawn onto.


Some things I notice: blocking. We need =stdout= to /react/ to incoming connections, but not wait and do nothing until connections come in. This is solveable already with =kqueue=.

** Okay, so, here's the plan

- All stdout gets drawn with PSF screen font to terminal window. (It's currently drawn directly to visible framebuffer).

I think we'll move the terminal and psf parts of =stdout= to a terminal process that does the regular "request window through the socket" sort of thing. That way we will fork()+exec() =stdout= into =stdout= and that terminal process, where =stdout= goes on to repaint the screen, handle incoming client connections, etc. in a loop. The terminal process will draw to *it's* framebuffer using the PSF screen font. The =stdout= process will draw all window's framebuffer's to the screen. Initially, it should be no different than what is happening now. We should just be able to have more than one window, technically.

- Each window displays something on the screen, so we can *see* how many there are and stuff, even if they are minimised or invisible or whatever.

* Flesh out the Network Stack
Low Priority

** ARP -- Address Resolution Protocol

This can get you a gateway address, which means you can talk to the rest of the world. Yay!

** UDP -- User Datagram Protocol

A very simple header you can bang on to just about any payload.

Technologies built on UDP:
- DHCP :: Dynamic Host Configuration Protocol
  This lets you get an IP address! Then you can respond to your very own ARPs.
- DNS :: Domain Name System
  This lets you turn human-readable URLs into computer-readable IPs!
- NTP :: Network Time Protocol
  This lets you sync your time with everyone else's time!
