/* Copyright 2022, Contributors To LensorOS.
 * All rights reserved.
 *
 * This file is part of LensorOS.
 *
 * LensorOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LensorOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LensorOS. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _LENSOROS_LIBC_CTYPE_H
#define _LENSOROS_LIBC_CTYPE_H

#include <bits/decls.h>

#ifdef _LIBC
#define __CONSTEXPR
#else
#define __CONSTEXPR __constexpr
#endif  // _LIBC

__BEGIN_DECLS__

__CONSTEXPR int isdigit(int c);
__CONSTEXPR int isalpha(int c);
__CONSTEXPR int isalnum(int c);
__CONSTEXPR int isxdigit(int c);
__CONSTEXPR int islower(int c);
__CONSTEXPR int isupper(int c);

__END_DECLS__

// If we aren't building libc, there is no need to ensure these get
// exported as symbols; try to define them in the header so calls to them
// never even get generated by the compiler.
#ifndef _LIBC
__constexpr inline int isdigit(int c) { return c >= '0' && c <= '9'; }
__constexpr inline int isalpha(int c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'); }
__constexpr inline int isalnum(int c) { return isalpha(c) || isdigit(c); }
__constexpr inline int isxdigit(int c) { return isdigit(c) || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'); }
__constexpr inline int islower(int c) { return c >= 'a' && c <= 'z'; }
__constexpr inline int isupper(int c) { return c >= 'A' && c <= 'Z'; }
__constexpr inline int tolower(int c) { return isupper(c) ? c + 'a' - 'A' : c; }
__constexpr inline int toupper(int c) { return islower(c) ? c - 'a' - 'A' : c; }
#endif  // _LIBC

#endif  // _LENSOROS_LIBC_CTYPE_H
