/* Copyright 2022, Contributors To LensorOS.
 * All rights reserved.
 *
 * This file is part of LensorOS.
 *
 * LensorOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LensorOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LensorOS. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _LENSOROS_LIBC_CTYPE_H
#define _LENSOROS_LIBC_CTYPE_H

#include <bits/decls.h>

#ifdef _LIBC

__BEGIN_DECLS__

int isdigit(int);
int isalpha(int);
int isalnum(int);
int isxdigit(int);
int islower(int);
int isupper(int);
int isascii(int);
int isblank(int);
int iscntrl(int);
int isgraph(int);
int isprint(int);
int ispunct(int);
int isspace(int);
int tolower(int);
int toupper(int);

__END_DECLS__

#else  // _LIBC

/** If we aren't building libc, there is no need to ensure these get
 ** exported as symbols; try to define them in the header so calls to them
 ** never even get generated by the compiler.
 **/

__constexpr static inline int isdigit(int c) { return c >= '0' && c <= '9'; }
__constexpr static inline int isalpha(int c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'); }
__constexpr static inline int isalnum(int c) { return isalpha(c) || isdigit(c); }
__constexpr static inline int isxdigit(int c) { return isdigit(c) || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'); }
__constexpr static inline int islower(int c) { return c >= 'a' && c <= 'z'; }
__constexpr static inline int isupper(int c) { return c >= 'A' && c <= 'Z'; }
__constexpr static inline int tolower(int c) { return isupper(c) ? c + 'a' - 'A' : c; }
__constexpr static inline int toupper(int c) { return islower(c) ? c - 'a' - 'A' : c; }
__constexpr static inline int isascii(int c) { return c < 128; }
__constexpr static inline int isspace(int c) { return c == ' '; }
__constexpr static inline int isblank(int c) { return isspace(c); }
__constexpr static inline int iscntrl(int c) { return c < ' ' || c == 127; }
__constexpr static inline int isprint(int c) { return c >= ' ' && c < 127; }
__constexpr static inline int isgraph(int c) { return c != ' ' && isprint(c); }
__constexpr static inline int ispunct(int c) {
    return (c >= 0x21 && c <= 0x2f)
           || (c >= 0x3a && c <= 0x40)
           || (c >= 0x5b && c <= 0x60)
           || (c >= 0x7b && c <= 0x7e);
}

#endif  // _LIBC

#endif  // _LENSOROS_LIBC_CTYPE_H
